# Authentication Logs
AUTH_LOGIN_ATTEMPT = "Login attempt for user: {username}"
AUTH_LOGIN_SUCCESS = "User {username} logged in successfully"
AUTH_LOGIN_FAILED = "Invalid credentials for user: {username}"
AUTH_REFRESH_ATTEMPT = "Refresh token attempt for user: {username}"
AUTH_REFRESH_SUCCESS = "New access token issued for user: {username}"
AUTH_REFRESH_FAILED = "Refresh token invalid or expired for user: {username}"
AUTH_ACCESS_TOKEN_BLACKLIST = "Access token blacklisted and cookie cleared"
AUTH_REFRESH_TOKEN_BLACKLIST = "Refresh token blacklisted and cookie cleared"
AUTH_INVALID_ACCESS_TOKEN_BLACKLIST = "Invalid access token, cannot blacklist"
AUTH_INVALID_REFRESH_TOKEN_BLACKLIST = "Invalid refresh token, cannot blacklist"
